name: TurkeyEvent
version: ${project.version}
main: com.hayes.turkeyevent.Main
api-version: 1.16
authors: [ Hayes ]
description: A plugin used for the Minecraft Server HungerMC during the Thanksgiving event
commands:
  relore:
    aliases: [rl]
    description: A command used for reloring items
  currenteggs:
    aliases: [ce]
    description: A command used for checking the amount of eggs you have opened during the Thanksgiving event
  highesteggs:
    aliases: [he]
    description: A command used for checking who has opened the largest amount of eggs
